"""
Problem 2
=========
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


from math import sqrt


MAX = 4000000

def ith_fib(i):
    return int((pow((1+sqrt(5))/2,i) - pow((1-sqrt(5))/2,i))/sqrt(5))

def solution():
    j   = 3
    res = 0
    while ith_fib(j) < MAX:
        res += ith_fib(j)
        j   += 3
    return res
